title: jared.im / Blog
email: contact@jared.im
description: I try to post interesting things here daily, but don't judge me if I miss a few days.
baseurl: /blog
url: https://jared.im
twitter_username: MrCrunkle
github_username: Crunkle

markdown: kramdown

permalink: pretty
timezone: Europe/London
